# Generated by Django 3.2.9 on 2021-11-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='column',
            field=models.PositiveBigIntegerField(verbose_name='column'),
        ),
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='user',
            field=models.UUIDField(verbose_name='user'),
        ),
    ]
