# Generated by Django 4.0.8 on 2023-07-12 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated UUID.', primary_key=True, serialize=False, unique=True, verbose_name='Internal UUID')),
                ('key', models.SlugField(db_index=False, help_text='The name for your custom field.', verbose_name='Key')),
                ('value', models.CharField(blank=True, help_text='The content of your custom field.', max_length=4096, verbose_name='Value')),
                ('object_id', models.UUIDField(editable=False)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'ordering': ['object_id'],
                'index_together': {('object_id', 'content_type'), ('content_type', 'key')},
            },
        ),
    ]
